# 1. Use a small sentence transformer
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
import joblib
import json
from tqdm import tqdm

### THIS CODE IS NOT RUN ###

### This is the code I used to train my model. It has at least partially been generated by AI.

model = SentenceTransformer('all-MiniLM-L6-v2')  # ~80 MB

with open("ai/motions.json", "r") as f:
    big_json = json.load(f)

train_texts = []
train_labels = []

print("creating lists")
for motion in tqdm(big_json):
    train_texts.append(motion["Infoslide"] + motion["Motion"])
    train_labels.append(motion["Types"])
    
# 2. Encode text
model = SentenceTransformer("all-MiniLM-L6-v2")
print("encoding")
X_train = model.encode(train_texts)

# 3. Encode labels
mlb = MultiLabelBinarizer()
y_train = mlb.fit_transform(train_labels)

# 4. Train multi‑label classifier
print("training")
clf = OneVsRestClassifier(LogisticRegression())
tqdm(clf.fit(X_train, y_train))

# 5. Predict
def classify(text):
    X = model.encode([text])
    pred = clf.predict(X)[0]
    categories = mlb.classes_[pred == 1].tolist()
    return categories

joblib.dump(model, "sentence_transformer.pkl")
joblib.dump(mlb, "multilabel_binarizer.pkl")
joblib.dump(clf, "classifier.pkl")

# Test
print(classify("The government should raise interest rates and protect free speech."))