import joblib
from fastapi import Request

# This code was at least partly generated by AI. 

def classify(info_slide: str, motion: str, request: Request):
    print("classify runs")  
    model = request.app.state.model
    mlb = request.app.state.mlb
    clf = request.app.state.clf
    
    print("model was gotten supposedly")
    # Encode text
    # This is the way I trained my model, but alter accordingly
    text = info_slide + motion
    X = model.encode([text])
    
    # Predict binary labels
    pred = clf.predict(X)[0]
    
    # Convert back to category names
    categories = mlb.classes_[pred == 1].tolist()
    
    return categories